from lxml import html
import requests
# improved spped and readability of requests compared to urllib2

page = requests.get('http://econpy.pythonanywhere.com/ex/001.html')
tree = html.fromstring(page.content)

# html looks like this
# <div title="buyer-name">Carson Busses</div>
# <span class="item-price">$29.95</span>

# This will create a list of buyers:
buyers = tree.xpath('//div[@title="buyer-name"]/text()')
# This will create a list of prices
prices = tree.xpath('//span[@class="item-price"]/text()')

print 'Buyers: ', buyers
print 'Prices: ', prices
# note: if the data you want from the html is generated by javascript, xpath wont work, you will need python-ghost or
# selenium
# you can also try https://github.com/scrapy/scrapely
